In [18]:
import pandas as pd
import numpy as np
import matplotlib as plt
import tensorflow as tf

In [19]:
tf.__version__

'2.20.0'

In [20]:
dataset = pd.read_csv('American_Express_User_Exit_Pred.csv')
x = dataset.iloc[:,0:-1].values
y = dataset.iloc[:, -1].values

In [21]:
print(x)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


## Gender Column - Label Encoding

In [22]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
x[:,2] = label_encoder.fit_transform(x[:,2])

In [23]:
print(x)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


## Geographical Column - One hot encoding

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [25]:
print(x)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.20 , random_state = 0)

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## ANN

In [29]:
# INITIALIZATION
ann = tf.keras.models.Sequential()

In [31]:
# Input layer and first hidden layer

ann.add(tf.keras.layers.Dense(units = 5, activation = 'relu'))

In [32]:
# Second hidden layer

ann.add(tf.keras.layers.Dense(units = 5, activation = 'relu'))

In [33]:
# Output Layer

ann.add(tf.keras.layers.Dense(units = 5, activation = 'sigmoid'))

### ANN Training